name: Test
on:
  push:
    branches:
      - main

jobs: 
  run_tests:
    name: running tests
    steps:
      - name: get_code
        uses: actions/checkout
      - name: cd
        run: cd gha-demo
      - name: dep_install
        run: npm install
      - name: run_tests
        run: npm run test