name: First_workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: printing
        run: |
            echo "this is first script"
            echo "this is second script"
