name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  run_tests:
    name: running tests
    runs-on: ubuntu-latest
    steps:
      - name: get_code
        uses: actions/checkout@v3
      - name: dep_install
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install_deps
        run: npm ci
      - name: run_tests
        run: npm run test
  deploy:
    needs: run_tests
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo deployed
        